const util = require("util");
const events = require("events");
const Cmd = function() {
  events.EventEmitter.call(this);
  const _this = this;
  this.handleEvent = function(evt, cmd, param) {
    var res = allCodes
      .filter(v => q.toLowerCase() == v[0].toLowerCase())
      .map(v => v[1])
      .join(", ");
    res = res == "" ? "ไม่พบเมลของท่าน" : res;
    _this.emit("replyMessage", {
      replyToken: evt.replyToken,
      message: {
        type: "text",
        text: res
      }
    });
  };
  util.inherits(Cmd, events.EventEmitter);
};
module.exports = Cmd;
var allCodes = [
  ["akarin_v@hotmail.com", "Code001"],
  ["anwaon@gmail.com", "Code002"],
  ["apichart@oneandallthailand.com", "Code003"],
  ["apiwat_manakij@hotmail.com", "Code004"],
  ["armsanova@gmail.com", "Code005"],
  ["artclicky@gmail.com", "Code006"],
  ["boatjapan@hotmail.com", "Code007"],
  ["bobnattee@gmail.com", "Code008"],
  ["bombernuke@outlook.com", "Code009"],
  ["boonchai.wanichayakorn@gmail.com", "Code010"],
  ["brae3988@hotmail.com", "Code011"],
  ["chaipetcharatn@gmail.com", "Code012"],
  ["chaiwat.m@pttgcgroup.com", "Code013"],
  ["chawinping@gmail.com", "Code014"],
  ["chokchai88@gmail.com", "Code015"],
  ["chothip.c@gmail.com", "Code016"],
  ["chryzaorz@gmail.com", "Code017"],
  ["ctanawat@gmail.com", "Code018"],
  ["daytripperzone83@gmail.com", "Code019"],
  ["Djantarawirot@gmail.com", "Code020"],
  ["dohciidohh@gmail.com", "Code021"],
  ["dohciidohh@gmail.com", "Code022"],
  ["ekasak.s@gmail.com", "Code023"],
  ["eranui@gmail.com", "Code024"],
  ["eve_mr.weerawat@hotmail.com", "Code025"],
  ["faifaiz89@gmail.com", "Code026"],
  ["hufflepuff@hotmail.com", "Code027"],
  ["jaihanz@hotmail.com", "Code028"],
  ["jannjant@hotmail.com", "Code029"],
  ["jirapongl@gmail.com", "Code030"],
  ["joeeng83@hotmail.com", "Code031"],
  ["julapong@yahoo.com", "Code032"],
  ["jxt117@gmail.com", "Code033"],
  ["k_pook@yahoo.com", "Code034"],
  ["k.kerdvibulvech@googlemail.com", "Code035"],
  ["kanitta.ppkan@gmail.com", "Code036"],
  ["kantanat.c@gmail.com", "Code037"],
  ["karn_736@hotmail.com", "Code038"],
  ["kingintania82@hotmail.com", "Code039"],
  ["kobra01@gmail.com", "Code040"],
  ["kratic37@hotmail.com", "Code041"],
  ["krit.ktp@gmail.com", "Code042"],
  ["kyow_mootoo@hotmail.com", "Code043"],
  ["lanna_nua@yahoo.com", "Code044"],
  ["littlebid24@gmail.com", "Code045"],
  ["macsparow@hotmail.com", "Code046"],
  ["mai_vanisa@hotmail.com", "Code047"],
  ["mail2oak@yahoo.com", "Code048"],
  ["mail2sompop@gmail.com", "Code049"],
  ["momo11132@hotmail.com", "Code050"],
  ["mrtanit@gmail.com", "Code051"],
  ["mtg_got@hotmail.com", "Code052"],
  ["n.chondarong@gmail.com", "Code053"],
  ["n.chondarong@gmail.com", "Code054"],
  ["N.PORNTEPARAK@GMAIL.COM", "Code055"],
  ["natanunt@gmail.com", "Code056"],
  ["natanunt@gmail.com", "Code057"],
  ["nattapolz1993@gmail.com", "Code058"],
  ["natthabox@gmail.com", "Code059"],
  ["ngamlertlees@gmail.com", "Code060"],
  ["nirachet@gmail.com", "Code061"],
  ["niwat@propertist.co.th", "Code062"],
  ["ohmaero@gmail.com", "Code063"],
  ["p.tonzon@gmail.com", "Code064"],
  ["pakawas.pm@gmail.com", "Code065"],
  ["pakieat@mitrproject.co.th", "Code066"],
  ["panchoak.a@pttgcgroup.com", "Code067"],
  ["panthep@gmail.com", "Code068"],
  ["pataradaoom@gmail.com", "Code069"],
  ["pavadee@thaioilgroup.com", "Code070"],
  ["pmcnarin@ksc.th.com", "Code071"],
  ["pnainapa@yahoo.com", "Code072"],
  ["poa.k@hotmail.com", "Code073"],
  ["Pongsupat@hotmail.com", "Code074"],
  ["pornsaks@gmail.com", "Code075"],
  ["pornthep689@gmail.com", "Code076"],
  ["prachayon@gmail.com", "Code077"],
  ["pradchaya.thepvorrachai@gmail.com", "Code078"],
  ["prateep@satiafy.co.th", "Code079"],
  ["prmmai@gmail.com", "Code080"],
  ["pthimasan@gmail.com", "Code081"],
  ["pthummawan@gmail.com", "Code082"],
  ["pton27@gmail.com", "Code083"],
  ["r_chatchai@hotmail.com", "Code084"],
  ["rabinhpp2542@gmail.com", "Code085"],
  ["roonglit@gmail.com", "Code086"],
  ["s1_63@hotmail.com", "Code087"],
  ["sayhellokorn@gmail.com", "Code088"],
  ["sbstur@yahoo.com", "Code089"],
  ["semicolonth@gmail.com", "Code090"],
  ["singsiri@gmail.com", "Code091"],
  ["sira.tindukasiri@gmail.com", "Code092"],
  ["sittikorn.kittisopawadee@gmail.com", "Code093"],
  ["smink80@hotmail.com", "Code094"],
  ["soontornlao@hotmail.com", "Code095"],
  ["sophon_poo@hotmail.com", "Code096"],
  ["soysejin@gmail.com", "Code097"],
  ["Supachai.lek.cu@gmail.com", "Code098"],
  ["supakit.sarootsikan@gmail.com", "Code099"],
  ["supara@padungsilpa.com", "Code100"],
  ["supara@padungsilpa.com", "Code101"],
  ["supara@padungsilpa.com", "Code102"],
  ["suppakitp@gmail.com", "Code103"],
  ["SURACHAIJARI@HOTMAIL.COm", "Code104"],
  ["taepeerapat@gmail.com", "Code105"],
  ["tantipats@yahoo.com", "Code106"],
  ["tasinchai@gmail.com", "Code107"],
  ["teeradejb@gmail.com", "Code108"],
  ["teerapat.sakhonsteel@gmail.co", "Code109"],
  ["teerapon.samp@gmail.com", "Code110"],
  ["tengchoosak@gmail.com", "Code111"],
  ["thaidroids@gmail.com", "Code112"],
  ["thailand.piggy@gmail.com", "Code113"],
  ["thanakrit.thavornamornsri@gmail.com", "Code114"],
  ["thanapk@mtec.or.th", "Code115"],
  ["thanapol.poosuwan@gmail.com", "Code116"],
  ["theerats@yahoo.com", "Code117"],
  ["tor4tam@gmail.com", "Code118"],
  ["tuangbhat.t@gmail.com", "Code119"],
  ["u.natthawat@gmail.com", "Code120"],
  ["urng843@gmail.com", "Code121"],
  ["vudol69@gmail.com", "Code122"],
  ["wasinie@gmail.com", "Code123"],
  ["watcharakhom@yahoo.com", "Code124"],
  ["weerawat@dpsea.co.th", "Code125"],
  ["wichotew@gmail.com", "Code126"],
  ["wichotew@gmail.com", "Code127"],
  ["wittayac@hotmail.com", "Code128"],
  ["woravit_u@yahoo.com", "Code129"],
  ["yaija47@hotmail.com", "Code130"],
  ["yanyong@padungsilpa.com", "Code131"],
  ["yossawaj.v@gmail.com", "Code132"],
  ["yunome.me@gmail.com", "Code133"]
];
